import os
from dotenv import load_dotenv
from openai import OpenAI
# Load environment variables from .env file
load_dotenv()

# Retrieve the OpenAI API key from the environment variables
openai_api_key = os.getenv("OPENAI_API_KEY")

# Set the OpenAI API key for OpenAI client
client = OpenAI(api_key=openai_api_key)
# Set OpenAI API Key directly or use environment variable
client = OpenAI()

def generate_answer(prompt: list, user_query: str) -> str:
    """
    Generate an answer using the OpenAI API.

    Args:
        prompt (list): The prompt to be sent to the OpenAI model for generating the response.
        user_query (str): The user's query, which can be used to modify the prompt.

    Returns:
        str: The answer generated by the model in response to the prompt.
    """

    # Send the request to OpenAI's chat completion API
    response = client.chat.completions.create(
        model="gpt-4o",  # Use the appropriate model, e.g., GPT-4
        messages=prompt,  # The conversation history or prompt to the model
        max_tokens=1500,   # Adjust token count as needed to manage the length of the response
        temperature=0.0,   # Set the temperature for deterministic responses (0.0 = most deterministic)
    )

    # Return the generated response, stripped of leading/trailing whitespace
    return response.choices[0].message.content.strip()
